version: '3.10'
services:
  db:
    image: postgres
    container_name: db_app
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: test_app
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
